pipeline {
	agent { 
		node {
      		label 'jenkins-slave1.yvu.ch'
    	}
	}
	stages {
		stage('Build') {
			steps {
				sh 'echo Build'
			}
		}

		stage('End2End Tests') {
		    steps {
		        sh 'echo End2End Tests'
		        sh ‘(cd Gadgeothek;.gradlew connectedAndroidTest)
		    }
		}

		stage('Package') {
		    steps {
		        sh 'echo Package'
		    }
		}
	}
}
